flags: {}
packages:
- '.'
- location:
    git: https://github.com/haskell-game/sdl2
    commit: 99d5e0974456b06d42e8cb9406c9a8cba55621cf
extra-deps:
- reactive-banana-0.8.1.2
- break-1.0.0
resolver: lts-3.2
